name: Build and deploy ASP.Net Core app to Azure Web App - losdiablillos

on:
  push:
    branches:
      - COPIA-ALEJANDRO
  workflow_dispatch:

env:
  API: ./src/AppForSEII2526.API/AppForSEII2526.API.csproj
  UT: ./test/AppForSEII2526.UT/AppForSEII2526.UT.csproj

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.API }}
          dotnet restore ${{ env.UT }}

      - name: Build projects
        run: |
          dotnet build ${{ env.API }} --configuration Release --no-restore
          dotnet build ${{ env.UT }} --configuration Release --no-restore

      - name: Run unit tests with report
        continue-on-error: true
        run: dotnet test ${{ env.UT }} --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Publish API
        run: dotnet publish ${{ env.API }} --configuration Release -o "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04B520E4FD794993B7DD7A0B0ECBD40E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_40FF49EAE2F14B4DBAD71D7DF7C423CC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2EA2A92B3D564622B39BE6753B44BCCE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'losdiablillos'
          slot-name: 'Production'
          package: .
